services:
    db:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASSWORD}
            - POSTGRES_DB=${PG_DATABASE}
        volumes:
            - pgdata:/var/lib/postgresql/data

    migration:
        build:
            context: .
        command: ["./wait-for-it/wait-for-it.sh", "db:5432", "--", "npm", "run", "prod:migrate:latest"]
        links:
            - db
        depends_on:
            - db
        env_file: ./.env
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASSWORD}
            - POSTGRES_DB=${PG_DATABASE}
    app:
        image: app
        build:
            context: .
        depends_on:
            - migration
            - db
        restart: always
        env_file: ./.env
        ports:
            - "3000:3000"
        environment:
            - GOOGLE_API_KEY=${GOOGLE_API_KEY}
            - WB_KEY=${WB_KEY}
            - PG_DATABASE=${PG_DATABASE}
            - PG_USER=${PG_USER}
            - PG_PASSWORD=${PG_PASSWORD}
            - SPREADSHEET_IDS=${SPREADSHEET_IDS}
        command: npm run prod

volumes:
    pgdata:
